### ISSUE TITLE
extra comma in bower.json (0.2.0)

### ISSUE THREAD

**Issue by polycentric** [addyosmani/polymer-filters#25]
It looks like there's an unwanted comma at the end of line 20 in bower.json v0.2.0 causing bower install to fail.

**Comment by arthurvr** [comment]
Fixed in https://github.com/addyosmani/polymer-filters/commit/659aa6c417f941a5e8f7118f8d519c2f900ed9c2.

**Comment by addyosmani** [comment]
:+1:
