### ISSUE TITLE
The currency filter is not international

### ISSUE THREAD

**Issue by masonlouchart** [addyosmani/polymer-filters#33]
Some currencies must have the sign after the price. Moreover, the thousand separator can be a point or a comma. Same thing for the decimals separator. It seems be a huge work to automate this feature, what about add separators parameters in a first time ?

``` javascript
currency(23.456, '€', 2) = "€23.46" // should be "23,46€"
currency(23456, '€', 2) = "€23,456.00" // should be "23 456,00 €"
```

We can also specify in the comment the method returns a rounded. Just to be clear.
_(sorry for my poor english)_

**Comment by skadimoolam** [comment]
Thanks @LM450N for mentioning this, I did not quite think of this while building it, let me see what I can do.

The best way to go about it would be to have an extra Parameter called "International" and set it to be true when needed.

It might look like:

```
currency(23.456, '€', 2) = "€23.46" // "€23,46"
currency(23456, '€', 2, true) = "€23,456.00" // "23 456,00 €"
```

Just one more thing:
 How would a number like `562356233` look like,
`562 356,233` or `562 356 233`

**Comment by chemzqm** [comment]
https://github.com/addyosmani/polymer-filters/blob/master/filter-currency.js#L14
If I set 0, the precision would be 2, seems wrong

**Comment by masonlouchart** [comment]
This issue is fairly old and there hasn't been much activity on it. ⌛
